### PR TITLE
Automatic translation doesn't work with a RichText editor

### PR DESCRIPTION
**Pull request by damianz5**
RichText is a separate bundle now https://github.com/ezsystems/ezplatform-richtext

https://jira.ez.no/browse/DEMO-286

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
I would to have some explanation. I am a little bit lost. :)

**Comment by Plopix** [comment]
it sounds like it is a namespace issue there is a new namespace now in place since the new bundle for Richtext for what I understand here ;) @damianz5 ?

**Comment by SylvainGuittard** [comment]
Got it! Thanks @Plopix :)

**Comment by damianz5** [comment]
ping @Plopix @SylvainGuittard final review please

**Comment by SylvainGuittard** [comment]
Good for me! +1

**Pull request merged**
